### ISSUE TITLE
Change travis to point to ropensci

### ISSUE THREAD

**Issue by sckott** [ropensci/rdopa#13]
Travis is activated for this repo, so I think we should change the travis button and travis file

**Comment by jlehtoma** [comment]
Thanks for noticing this, I've updated the travis button. Not sure what you mean with travis file, `.travis.yml` doesn't have any hard coded URLs in it?

**Comment by sckott** [comment]
woops, right, sorry, i meant add some lines for our purposes, e.g., https://github.com/ropensci/taxize/blob/master/.travis.yml#L12-L14 That okay?

**Comment by jlehtoma** [comment]
Ah, Slack notification for Travis builds. Cool, I added the lines as-is in `taxize`.

**Comment by jlehtoma** [comment]
Closing the issue.
