### ISSUE TITLE
Add AppVeyor configuration 

### ISSUE THREAD

**Issue by jlehtoma** [ropensci/rdopa#15]
Many rOpenSci packages have AppVeyor enabled for Windows (or .NET), which could be enabled for `rdopa` as well. This is probably more crucial for packages that need to compile something on the target platform, or depend on packages that are not necessarily stable on Windoze.

Any opinions, @sckott ?

**Comment by sckott** [comment]
We have this in most of our packages as a check to help catch any major problems on windows machines.  It's not crucial to have, but it's very easy to do. Up to you.
