### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by sckott** [ropensci/rdopa#18]
https://travis-ci.org/ropensci/rdopa/builds/49977752

@jlehtoma  Do you think you could fix this soon?

**Comment by jlehtoma** [comment]
Sorry about not reacting to this earlier, but it seems that the whole API is out, hence the tests failing (tests run against the API). Immediate fix would be to disable tests in TravisCI `r_check_args: --no-tests` . I'll do this and see what's going on in dopa.

**Comment by sckott** [comment]
@jlehtoma Okay, thanks for checking on it :)

**Comment by jlehtoma** [comment]
Seems like there has been restructuring of the rest services URL etc, I'll fix this ASAP.
