### ISSUE TITLE
Vignette build errors

### ISSUE THREAD

**Issue by sckott** [ropensci/rdopa#23]
I see that the travis file has no build vignettes, but I wonder why it doesn't build, e.g,. when trying to install I get 

```r
devtools::install_github("ropensci/rdopa", build_vignettes=TRUE)
#> ...
#> Quitting from lines 24-30 (rdopa_vignette.Rmd)
#> Error: processing vignette 'rdopa_vignette.Rmd' failed with diagnostics:
#> non-character argument
#> Execution halted
#> Error: Command failed (1)
```

is this something that can be fixed?

**Comment by jlehtoma** [comment]
Sure, I've fixed issues preventing the vignette build in various other things in 7dfe8035408fd7888e57f6e977ab90618d9f6634 and re-enabled the build at Travis as well. The DOPA API has changed quite a lot, so I'll be doing some more major changes + implementing new functions soon.

**Comment by sckott** [comment]
thanks!
