### ISSUE TITLE
package status?

### ISSUE THREAD

**Issue by sckott** [ropensci/rdopa#26]
Hi @jlehtoma what's status with this pkg?  Noticed that it's not on CRAN yet. Did you want to get it up there? Do you need any help ?

**Comment by jlehtoma** [comment]
Unfortunately I haven't had the time (or need) to develop this pkg in a while... Not sure about the current status of the API either. I could give it a go at some point, or alternatively, is there some sort of "retirement track" in rOpenSci?

**Comment by sckott** [comment]
opened a discussion here https://discuss.ropensci.org/t/retiring-ropensci-packages/827
